using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Problem2
{
    class Prob2
    {

        /*
          
           Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

            1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

            By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
         */

        static void Main(string[] args)
        {
            List<int> fibo = new List<int>();
            int nextTerm, solution = 0;

            fibo.Add(0);
            fibo.Add(1);

            while (fibo[fibo.Count - 1] < 4000000)
            {
                nextTerm = fibo[fibo.Count-2] + fibo[fibo.Count-1];
                fibo.Add(nextTerm);
            }

            for (int i = 0; i < fibo.Count; i++)
            {
                if (fibo[i] % 2 == 0 && fibo[i] < 4000000)
                {
                    solution += fibo[i];
                }
            }

            Console.WriteLine("solution: "+solution);

        }
        
    }
}
